### ISSUE TITLE
apk release

### ISSUE THREAD

**Issue by pabloscloud** [simonalveteg/Minute-Launcher#50]
Add apks to the release tab at least.

More over it would be nice to see this app on f-droid.

**Comment by simonalveteg** [comment]
Good suggestion, I've put off adding releases for a while since there are some minor bugs that I haven't gotten around to fixing, but once I've gotten around to it I'll definitely add a release. F-Droid has been on my mind for a while but I think that will wait until I get a bit closer to what I would consider version 1.0 :p

**Comment by pabloscloud** [comment]
My app is on fdroid and play store despite me considering it not being version 1 😅 But I totally get that then

**Comment by simonalveteg** [comment]
hey @pabloscloud thought I'd let you know that I just added a release (half a year later..) if you're still interested in checking it out!

**Comment by pabloscloud** [comment]
omg nice
